### ISSUE TITLE
Allow ! on non-boolean varibles

### ISSUE THREAD

**Issue by DarkoKukovec** [infinum/js-linters#12]

**Comment by DarkoKukovec** [comment]
That's actually something we should discuss...

Should we allow `!!something` instead of `Boolean(something)`?

**Comment by andreicek** [comment]
`Boolean(smth)` is more verbose and in line with the language.

**Comment by fvoska** [comment]
Personally I am OK with this in JavaScript:
```javascript
const foo = {};
if (foo) { ... }
if (!foo) { ... }
```

Historically in TypeScript, I had the rule [strict-boolean-expressions](https://palantir.github.io/tslint/rules/strict-boolean-expressions/) enabled, but after some time I disabled it because it was a bit annoying.

But I think that in TS we should actually cast to boolean in cases like this example:
```typescript
class AuthService {
  public user: User;

  public get isUserLoggedIn(): boolean {
    return Boolean(this.user);
  }
```
